// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/lzaun/iam/config"
	"github.com/lzaun/iam/internal/router"
	"github.com/lzaun/iam/internal/server"
)

// Injectors from wire.go:

func Init() *server.Server {
	configConfig := config.NewConfig()
	handler := router.NewRouter(configConfig)
	serverServer := server.NewServer(configConfig, handler)
	return serverServer
}

// wire.go:

var serverSet = wire.NewSet(server.NewServer)

var routerSet = wire.NewSet(router.NewRouter)

var configSet = wire.NewSet(config.NewConfig)
