// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/lantonster/iam/config"
	"github.com/lantonster/iam/internal/handler"
	"github.com/lantonster/iam/internal/repo"
	"github.com/lantonster/iam/internal/router"
	"github.com/lantonster/iam/internal/server"
	"github.com/lantonster/iam/internal/service"
)

// Injectors from wire.go:

func Init() *server.Server {
	configConfig := config.NewConfig()
	repoRepo := repo.NewDefaultRepo(configConfig)
	serviceService := service.NewService(repoRepo)
	handlerHandler := handler.NewHandler(serviceService)
	httpHandler := router.NewRouter(configConfig, handlerHandler)
	serverServer := server.NewServer(configConfig, httpHandler)
	return serverServer
}

// wire.go:

var serverSet = wire.NewSet(server.NewServer)

var routerSet = wire.NewSet(router.NewRouter)

var handlerSet = wire.NewSet(handler.NewHandler)

var serviceSet = wire.NewSet(service.NewService)

var repoSet = wire.NewSet(repo.NewDefaultRepo)

var configSet = wire.NewSet(config.NewConfig)
