// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/lzaun/iam/config"
	"github.com/lzaun/iam/internal/server"
)

// Injectors from wire.go:

func Init() *server.Server {
	configConfig := config.NewConfig()
	serverServer := server.NewServer(configConfig)
	return serverServer
}

// wire.go:

var serverSet = wire.NewSet(server.NewServer)

var configSet = wire.NewSet(config.NewConfig)
